#!/usr/bin/env bash

# This following functions were originally taken from -
# https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh
#
#   These functions echoes a bunch of 24-bit color codes
#   to the terminal to demonstrate its functionality.
#   The foreground escape sequence is ^[38;2;<r>;<g>;<b>m
#   The background escape sequence is ^[48;2;<r>;<g>;<b>m
#   <r> <g> <b> range from 0 to 255 inclusive.
#   The escape sequence ^[0m returns output to default

function _setBackgroundColor()
{
    printf '\x1b[48;2;%s;%s;%sm' $1 $2 $3
}

function _resetOutput()
{
    echo -en "\x1b[0m\n"
}

# Gives a color $1/255 % along HSV
# Who knows what happens when $1 is outside 0-255
# Echoes "$red $green $blue" where
# $red $green and $blue are integers
# ranging between 0 and 255 inclusive
function _rainbowColor()
{
    let h=$1/43
    let f=$1-43*$h
    let t=$f*255/43
    let q=255-t

    if [ $h -eq 0 ]
    then
        echo "255 $t 0"
    elif [ $h -eq 1 ]
    then
        echo "$q 255 0"
    elif [ $h -eq 2 ]
    then
        echo "0 255 $t"
    elif [ $h -eq 3 ]
    then
        echo "0 $q 255"
    elif [ $h -eq 4 ]
    then
        echo "$t 0 255"
    elif [ $h -eq 5 ]
    then
        echo "255 0 $q"
    else
        # execution should never reach here
        echo "0 0 0"
    fi
}


function colorgrid() {
    local iter=16
    while [[ $iter -lt 52 ]]; do
        local second=$(($iter+36))
        local third=$(($second+36))
        local four=$(($third+36))
        local five=$(($four+36))
        local six=$(($five+36))
        local seven=$(($six+36))
        if [[ $seven -gt 250 ]];then
            local seven=$(($seven-251));
        fi

        echo -en "\033[38;5;${iter}m█ "
        printf "%03d" $iter
        echo -en "   \033[38;5;${second}m█ "
        printf "%03d" $second
        echo -en "   \033[38;5;${third}m█ "
        printf "%03d" $third
        echo -en "   \033[38;5;${four}m█ "
        printf "%03d" $four
        echo -en "   \033[38;5;${five}m█ "
        printf "%03d" $five
        echo -en "   \033[38;5;${six}m█ "
        printf "%03d" $six
        echo -en "   \033[38;5;${seven}m█ "
        printf "%03d" $seven

        iter=$(($iter+1))
        printf '\033[00m\r\n'
    done

    echo
    awk 'BEGIN{
        s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
        for (colnum = 0; colnum<77; colnum++) {
            r = 255-(colnum*255/76);
            g = (colnum*510/76);
            b = (colnum*255/76);
            if (g>255) g = 510-g;
            printf "\033[48;2;%d;%d;%dm", r,g,b;
            printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
            printf "%s\033[0m", substr(s,colnum+1,1);
        }
        printf "\n";
    }'

    # Display all(?) 24bit colors
    echo

    for i in `seq 0 127`; do
        _setBackgroundColor $i 0 0
        echo -en " "
    done
    _resetOutput
    for i in `seq 255 -1 128`; do
        _setBackgroundColor $i 0 0
        echo -en " "
    done
    _resetOutput

    for i in `seq 0 127`; do
        _setBackgroundColor 0 $i 0
        echo -n " "
    done
    _resetOutput

    for i in `seq 255 -1 128`; do
        _setBackgroundColor 0 $i 0
        echo -n " "
    done
    _resetOutput

    for i in `seq 0 127`; do
        _setBackgroundColor 0 0 $i
        echo -n " "
    done
    _resetOutput
    for i in `seq 255 -1 128`; do
        _setBackgroundColor 0 0 $i
        echo -n " "
    done
    _resetOutput

    for i in `seq 0 127`; do
      _setBackgroundColor `_rainbowColor $i`
      echo -n " "
    done
    _resetOutput

    for i in `seq 255 -1 128`; do
      _setBackgroundColor `_rainbowColor $i`
      echo -n " "
    done
    _resetOutput

}

colorgrid "$@"
